// Generates lib/secrets.js from .env so tokens never live in tracked files.
// lib/secrets.js is git-ignored but deployed with the other lib/ modules.
import fs from 'node:fs';

const env = Object.fromEntries(
  fs.readFileSync(new URL('../.env', import.meta.url), 'utf8')
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('#') && l.includes('='))
    .map((l) => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim()]),
);

if (!env.BALE_BOT_TOKEN) {
  console.error('BALE_BOT_TOKEN is missing in .env');
  process.exit(1);
}

fs.writeFileSync(
  new URL('../lib/secrets.js', import.meta.url),
  '// GENERATED by scripts/gen-secrets.mjs from .env — do not commit.\n' +
  `export const BALE_TOKEN = ${JSON.stringify(env.BALE_BOT_TOKEN)};\n`,
  { mode: 0o600 },
);
console.log('lib/secrets.js written');
